export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const FETCH_NOTEBOOKS_START = 'FETCH_NOTEBOOKS_START';
export const FETCH_NOTEBOOKS_SUCCESS = 'FETCH_NOTEBOOKS_SUCCESS';
export const FETCH_NOTEBOOKS_FAIL = 'FETCH_NOTEBOOKS_FAIL';

export const FETCH_NOTEBOOK_START = 'FETCH_NOTEBOOK_START';
export const FETCH_NOTEBOOK_SUCCESS = 'FETCH_NOTEBOOK_SUCCESS';
export const FETCH_NOTEBOOK_FAIL = 'FETCH_NOTEBOOK_FAIL';

export const FETCH_NOTE_START = 'FETCH_NOTE_START';
export const FETCH_NOTE_SUCCESS = 'FETCH_NOTE_SUCCESS';
export const FETCH_NOTE_FAIL = 'FETCH_NOTE_FAIL';

export const POST_NOTE_START = 'POST_NOTE_START';
export const POST_NOTE_SUCCESS = 'POST_NOTE_SUCCESS';
export const POST_NOTE_FAIL = 'POST_NOTE_FAIL';

export const UPDATE_NOTE_START = 'UPDATE_NOTE_START';
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';
export const UPDATE_NOTE_FAIL = 'UPDATE_NOTE_FAIL';

export const REMOVE_NOTE_START = 'REMOVE_NOTE_START';
export const REMOVE_NOTE_SUCCESS = 'REMOVE_NOTE_SUCCESS';
export const REMOVE_NOTE_FAIL = 'REMOVE_NOTE_FAIL';
